import Head from "next/head";
import Image from "next/image";
import Card from "../components/ContentCard";
import Layout from "../components/Layout";
import MainCard from "../components/MainCard";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { Content } from "../data/globalSupply.json";
export default function Home() {
  console.log(Content.Content);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <MainCard />
        {Content.map((obj,index) => (
          <Card key={index} title={obj.title} content={obj.content} right={obj.right} />
        ))}
      </Layout>
    </div>
  );
}
